// Original Chinese summaries. Sources are attached to each generated catalog record.
export const summaries = {
 'Harmonic Booster':'干净前级与音色塑形。Boost 管音量，Character 管整体染色，中频可以单独选频率再提升或削减。适合给原本的贝斯音色增加存在感，而不是制造明显失真。',
 'Leo Bass':'以音箱式前级控制塑造贝斯基础音色。Volume、Master 与三段均衡分工不同：先确定输入推动程度，再用 Master 配平响度。',
 'Jim Bass':'贝斯前级模型，提供 Volume、Master 和三段均衡。可以放在箱体前，作为整条音色链的基础。',
 'Gentle':'控制简单的贝斯前级：低频、高频加一个低切开关。适合快速修整厚度和明亮度；Low Cut 用来减少不必要的低频。',
 '70s Peggy':'复古贝斯音箱模型。用 Ultra Lo／Ultra Hi 切换宽范围音色，再用中频档位决定突出身体感还是清晰度。旧版名称为 Peggy Bass。',
 'Peggy Fliptop':'复古翻盖式贝斯音箱模型。Volume 与 Bass、Treble 构成主要音色控制，Output Level 用来匹配最后的响度。',
 'Peggy Classic':'经典贝斯音箱模型，带输入衰减、增益、五档中频选择和高低频增强开关。比 70s Peggy 提供更多增益结构控制。',
 'Super California':'贝斯音箱模型。通过输入音量、三段均衡与 Master 调整基础音色；适合与箱体模拟搭配直出。',
 'Kallinen Kruukkeri':'带四段均衡的贝斯音箱模型。低中频与高中频可以分开调，Mid Contour 切换整体中频轮廓。',
 'Tiny Lark III':'贝斯音箱模型，完整旧名 Black & Yellow Tiny Lark III。除了四段均衡，还能用 Modern Filter 与 Vintage Filter 快速改变整体音色轮廓。',
 'SWIRL-900':'多段半参数均衡的贝斯音箱模型。低中、中、高中三个区域可以分别选频率，便于细调闷感、鼻音与弦头细节。',
 'SWE TC650':'贝斯音箱模型，组合基础均衡、可选中频、明亮度与驱动控制。可以从干净音色逐步加入管式染色。',
 'Modern ISOBRICK 750':'现代贝斯音箱模型。被动中频与主动中频分开控制，并提供可调中频频率，适合精细塑造厚度和穿透力。',
 'Modern ISOBRICK 750 OD':'ISOBRICK 的过载版本。在基础均衡之外增加 Overdrive，用于加入颗粒与饱和，再配平输出音量。',
 'Fruity HB 500':'贝斯音箱模型，提供增益、过载开关和三段均衡。可从基础音箱音色切换到更有驱动感的声音。',
 'Entropia':'三频段失真处理器。低频可单独压缩，中频和高频可以使用不同失真类型，既保住低频支撑，也能加出清晰的失真层次。',
 'Microtubes B3K':'现代贝斯过载。Drive 决定失真量，Grunt 和 Mid Boost 塑造重心，Blend 把干净低频混回来。',
 'Vintage Microtubes':'复古贝斯过载。Drive 决定饱和度，Era 从温暖的复古色彩转向更紧实、更明显的中高频；Blend 保留干净信号。',
 'Alpha Omicron':'在 Alpha 与 Omega 两种失真性格之间混合。Growl 增加低频重心，Bite 增强咬合感，适合从粗颗粒到激烈失真。',
 'Duality Fuzz':'双性格 Fuzz。Duality 在两种毛刺声音之间过渡，Filter 修整高频，Blend 保留原始贝斯的轮廓。',
 'Chinchilla':'失真单块，提供 Distortion、Tone、Blend 与 Volume。可以用少量干声保留低频和触弦细节。',
 'Microtubes X':'把低频与高频分开处理。低频用压缩维持扎实，高频单独失真；两个分频控制决定哪些频率进入哪一路。',
 'Atomic Sans':'带主动音色塑形的贝斯驱动。除了 Drive、Blend，还可切换低频与中频工作点，适合做完整的驱动型基础音色。',
 'Green PiRate Fuzz':'Fuzz 音色，配有可开关的 Tone 音色电路和干湿混合。用 Blend 保住低频，同时加上厚重的毛边。',
 'Bee Kolme OD':'简洁的过载单块。Gain 控制推动程度，高低频均衡修整音色，Blend 将干声与效果声混合。',
 'Arc Dreamer':'带高低频均衡的过载。适合用小 Drive 和适量 Blend 增加质感，也可以继续推高获得更明显的失真。',
 'Mood Fuzz':'带三段均衡与干湿混合的 Fuzz。可以分别修整低、中、高频，不必只依靠一个 Tone 旋钮。旧社区资料称 Mood 2。',
 'Ignissor':'三频段压缩器。低、中、高频分别控制动态，避免低音弦的大能量把整段音色一起压下去；Solo 可以单独监听频段。',
 'FET Compressor':'FET 风格压缩器。Input 改变送入压缩电路的电平，Output 补偿音量，Blend 可做并行压缩。刻度不是直接的毫秒值。',
 'BUS Compressor':'总线式压缩器。通过阈值、比例和时间参数把演奏动态收拢，Blend 可以保留干声的触弦感。',
 'Compressor / Limiter':'通用压缩／限制器。比例越大，越接近强力限制峰值；Knee 决定压缩开始时是柔和过渡还是明显介入。',
 'Amp EQ':'四段音箱式均衡，其中低中频、高中频可选频率。适合快速修整音色而不需要复杂的均衡器。',
 'Darkglass 6-Band EQ':'六段图示均衡，低／高端是搁架式，中央频段针对音色细节。适合快速修整低频、浑浊感和拨弦存在感。',
 'Generic 6-Band EQ':'100 Hz 至 3.2 kHz 的六段图示均衡。每段独立增减，适合直观地找到需要保留或削弱的声音区域。',
 'Parametric EQ':'六段参数均衡。先选频率，再控制增减与宽度；适合准确处理某段轰鸣或刺耳，而不是一口气改变整片频率。',
 'Hi-Pass + Lo-Pass Filter':'把高通与低通合到一个单块：高通削低频轰鸣，低通收掉最上端的毛刺。注意高通是让高频通过，不是增加高频。',
 'Hi-Pass Filter':'高通，也叫低切。切掉设定频率以下的声音；适合控制超低频轰鸣，截止点开得过高会让贝斯变薄。',
 'Lo-Pass Filter':'低通，也叫高切。切掉设定频率以上的声音；适合收敛指噪、失真毛刺和过亮的高频。',
 'Gravitron':'随演奏力度变化的包络滤波器。轻重手会产生不同的扫频动作，适合 Funk、自动哇音和合成器感音色。',
 'mo**erf***r':'带输入驱动和共振控制的包络滤波器。可以在随触弦摆动的滤波和更固定的合成器式音色之间调整。',
 'Noise Suppressor':'噪声抑制。根据阈值压低弱信号区的噪音；阈值过高也可能损失轻弹与尾音。',
 'Nembrini Audio Noise Gate':'噪声门，控制低于阈值时的衰减。适合清理高增益间隙，不会把你正在演奏时的全部底噪单独分离掉。',
 'Wauwa':'手动位置控制的哇音。把 Position 分配给表情踏板即可边弹边扫频；也可以固定一个位置作为特别的滤波音色。',
 'Axioma':'1.18.0 新增的单音合成器。追踪贝斯／吉他音高，驱动两个振荡器与低八度振荡器，再经过滤波、包络和琶音器。单音清楚地弹更容易追踪。',
 'Mint Chocolate Chorus':'合唱效果：把轻微变化的音高与原声混合，让音色更宽、更有流动感。Rate 管速度，Depth 管摆动幅度。',
 'Flamingo Flanger':'镶边效果。非常短的延迟与原声干涉，形成移动的梳状滤波；Feedback 调大时会更明显、更有喷气感。',
 'Sublime Octaver':'单音八度效果，用原声与八度声的比例塑造更厚的音色。和弦不是主要用途，清楚的单音有助于稳定追踪。',
 'Sublemon Octaver':'单音八度效果，提供干声、八度声和滤波。可以与压缩、滤波搭配做合成器感贝斯；请用耳朵比较它与 Sublime 的性格。',
 'Subcitri Octaver':'复音八度效果，可处理比单音八度更复杂的演奏。调整八度声与干声比例，再用滤波修整效果声的亮度。',
 'Pitch Shifter':'按半音与音分移调。既能整体变调，也能混入原声形成固定音程；它不会自动依据歌曲和声选择音阶内的音。',
 'Pharos Phaser':'相位效果，通过多级相位处理制造流动的凹口。Stages 改变复杂程度，Feedback 增强扫动色彩。',
 'Tremora Tremolo':'颤音：音量周期性变大变小，不是音高上下摆动。可以从轻微呼吸感调到明显切分。',
 'Vibralis Vibrato':'颤音高：让音高周期性上下摆动。区别于 Tremolo 的音量变化，可用于轻微漂移或明显的摇晃感。',
 'Pitch Bender':'连续弯音。Max Shift 决定最大音程，Shift Amount 决定走到哪一步；适合分配给表情踏板。',
 'Digital Delay':'清晰重复的数字延迟。Time 与 Range 决定间隔，Feedback 决定重复量，Subdivision 可让节奏跟随速度。',
 'Analog Delay':'带模拟风格音色的延迟，适合更柔和的重复。先调重复间隔，再用 Blend 控制原声后面跟多少回声。',
 'Modulation Delay':'带调制与高低切的延迟。可以给回声增加轻微摇晃，也能把回声处理得更暗、更薄，给原声让出位置。',
 'Room Reverb':'房间混响，给声音增加较近的空间感。少量使用可以让直录音色不那么干。',
 'Plate Reverb':'板式混响，提供密集而平滑的尾音。适合希望听到明显混响质感、又不强调某个真实房间的时候。',
 'Hall Reverb':'大厅混响，适合较大空间与长尾音。贝斯上可适当削掉混响低频，避免持续音堆积。',
 'Shimmer Reverb':'带移调色彩的混响，适合空灵铺底和环境音色。效果声宜从少量开始，避免盖住清楚的音头。',
 'Spring Reverb':'弹簧式混响。Length、Tension 与 Tone 调整长度和质感，适合带复古感、带弹性纹理的空间声音。',
 'Tone 3000':'加载 TONE3000 捕捉模型的入口，不是固定一种音色。先选 NAM 模型，再匹配输入输出；Full／Lite 的选择会影响资源占用与模型处理。',
 'User cabinet IR loader':'加载你导入的箱体脉冲响应。IR 用来表现箱体与拾音链的频率／时间响应，不等于完整的动态失真音箱模型。',
 'Neural Amp Loader':'加载神经网络音箱捕捉，并带均衡控制。Input 会影响模型被推动的程度，Output 用于配平音量。',
 'Neural Pedal Loader':'加载单块捕捉模型。通过 Input、Output、Blend 控制驱动强度和干湿比例；具体性格取决于所选文件。',
 'Neural Loader':'通用神经模型加载器。选择模型后主要控制输入和输出，不自带一套固定音箱旋钮。',
 'Gain':'纯电平工具，0 dB 为不增不减。放在失真前可能改变失真程度，放在链尾主要改变最终音量；还可以反转极性。',
 'Volume Pedal':'音量踏板单块，可把 Volume 绑定到表情踏板。放在混响前能保留空间尾音，放在链尾会连尾音一起控制。',
 'Output':'选择这一路信号送往哪些物理输出与耳机。用于给舞台音箱、调音台或监听安排不同的输出路线。',
 'Split':'把信号分到两行。可调整每行音量，或按频率高低分流，适合做干净低频＋失真高频等并行处理。',
 'Merge':'把两行信号汇合。Blend 调整两路比例，Level 控制合并后的电平；注意不同路径的相位关系可能影响音色。',
 'Send':'控制送往外部设备的信号与继续沿内部链路走的信号。用于连接外部单块或其他音频设备。',
 'Return':'把外部返回信号混入当前链路，可调整混合、输出与返回极性。先确认外部设备电平匹配。',
 'FX Loop':'把发送和返回合在一个效果环路单块里。可控制发送音量、回路混合与输出，把实体单块插入 Anagram 链路。',
 'Rocker 83':'80 年代 Rockman 风格失真。Edge 偏轻颗粒，Dist 更饱和；Gain、Treble、Volume 分别控制驱动、亮度和音量。',
 'Lead Trilogy':'三种英式高增益音色：Jubilee、800、900。Mode 换性格，Gain 决定饱和度，适合摇滚节奏与主奏。',
 'Plexi Breed':'三种 Plexi 风格模型。Normal 与 High Treble 两路增益可以混合，Mode 在 JTM、1959 与 1987 之间选择。',
 'RMPro':'带低高频、驱动、输出上限和立体声扩展的增强处理器。适合链尾整体修整；要用相近响度比较，避免把更响误听成更好。',
 'faIR MEGA California Recto':'以 Rectifier 4×12 箱体采样为基础的吉他箱体 IR 集合。可选不同拾音组合及 Tube、Solid、SPARC 性格。',
 'faIR Marsh 1960':'Marshall 1960A 风格箱体 IR 集合，面向摇滚吉他音色。Model 选择采样，Mode 选择不同处理性格。',
 'faIR ENG 212':'封闭式 2×12、Vintage 30 风格箱体 IR 集合，适合高增益摇滚／金属。用 Model 和 Mode 比较不同拾音结果。',
 'faIR Modern Rock':'面向现代摇滚的混合箱体 IR 集合。每个模型已组合多支麦克风，适合快速挑选可用的箱体音色。',
 'faIR Post Grunge':'后垃圾摇滚方向的多箱体混合 IR。选择模型即可切换已制作好的拾音组合，不需要自己逐支混麦。',
 'faIR Modern Metal':'面向现代金属的多麦克风混合 IR。适合接在高增益音箱／前级后面，完成直出音色。',
 'Gaffa':'磁带延迟，强调饱和、老化、褶皱与速度不稳定的个性。可以从轻微温暖调到明显摇晃的 Lo-Fi 回声。',
 'Phantom Zone':'80 年代 Dimension 风格合唱。用四档强度制造宽阔但不剧烈摇晃的立体声，控制非常简洁。',
 'Overtone WAH-1':'随触弦力度动作的复古哇音／包络滤波。Sensitivity 决定你的轻重手如何触发扫频。',
 'Overtone PH-1':'复古相位效果。以 Speed 调整流动速度，从轻微色彩到明显旋转感。',
 'Overtone CR-1':'复古模拟风格合唱。Speed 管流动速度，Depth 管摆动幅度。',
 'Overtone DT-1':'模拟风格驱动，从轻微延音、蓝调式过载到更粗的 Fuzz 色彩；Drive 与 Level 分别调整质感和音量。',
 'Shiroverb MKII':'带可选移调音程的 Shimmer 混响。能分别控制早期反射、尾音、预延迟和空间大小，适合环境铺底。',
 'DoGood Reverbs':'真实空间与设备混响的 IR 选集。选好 IR 后调干湿电平；高通可减少混响的低频堆积。',
 'Pedal Taster':'Colombo 单块的免费固定捕捉合集。Pedal 选择不同声音，Input／Output 调电平；它不是每个原型全旋钮可调的版本。',
 'Tetraplopia Doubler':'四声部立体声加倍器。每个声部可单独调音量、声像、延迟和微小移调。输入会先合为单声道，不保留前一级原本的立体声信息。',
 'Cosmic Milk Chorus':'合成器风格的宽阔合唱。分频保护低频，Rate 联动调制速度与深度；输入先合为单声道再生成立体声。',
 'Amp Squeezer Overdrive':'频率塑形过载。Heat 把驱动重点从明亮高频移向温暖低频，Mix 保留原声。',
 'Bassement Plague Distortion':'可在两种失真性格之间连续变化的单块。Fat 负责性格混合，Filter 修整声音，Mix 保住原声。',
 'Bassknob STD':'简化操作的贝斯录音链：管式音箱、Clean／Dirt 通道与可关闭的箱体／IRDX。适合快速获得完整基础音色。',
 'Ampknob RevC':'高增益 RevC 风格吉他音箱，前端已加入用于收紧音色的过载。可关闭内置箱体，搭配自己的 IR。',
 'Hardball':'ENGL Powerball II 风格四通道吉他音箱。Clean、Crunch 与两路 Lead 各有控制，另带箱体与麦克风设置。',
 'Black':'RAT2 风格失真。Drive 加大失真，Filter 修整高频，Level 配平输出。',
 'Clon Minotaur':'Klon 风格过载。低 Gain 可作为轻度染色／推动前级，高 Gain 增加明显过载，Treble 调亮度。',
 'Crunck V2':'免费单通道吉他音箱，从较轻增益到高增益均可探索。可选内置 4×12 箱体或关闭后另接 IR。',
 '808 Overdrive Pro':'TS808 风格过载。Drive、Tone、Level 三旋钮，适合直接过载或放在音箱前推动增益。',
 'Nine Gates Diabolic Distortion':'面向金属的原创高增益前级，双增益阶段与三段均衡配合，Edge 用于修整失真边缘。',
 'PSA1000 Analog Saturation Unit':'90 年代模拟前级风格饱和器。Buzz、Punch、Crunch 改变不同频率的驱动性格，也可用干湿混合进行并行处理。',
 '501 Chorus Echo':'把磁带回声、BBD 合唱与弹簧混响组合在一起。可分开调各效果音量，制作复古宽阔音色。',
 'Pirkko Chorus Deluxe':'保留贝斯低频的合唱。Intensity 添加效果层，Width 控制音高摆动深度，分频用于保持低音主体清晰。',
 'SmulTron III Envelope Filter':'力度触发的 Funk 包络滤波。Sensitivity、Peak、Decay 分别影响触发、共振和收回速度。',
 'Bass Driver':'三频段驱动型贝斯音箱。低中高各自处理增益、压缩、混合与电平，再搭配均衡、箱体和 DI 路径。',
 'Bass Hammer':'Tone Hammer 风格贝斯音箱，带 AGS 驱动塑形、可调中频、图示均衡以及箱体／DI 处理。',
 'Auto Drummer':'自动鼓手。选节奏风格和速度，把 Action 分配给脚钉：启动后单击加花、双击停止、长按换段落。它是练习伴奏工具。',
 'QuadBass':'四频段贝斯音箱。各频段独立驱动与后级处理，另有前置、后置、低频压缩及噪声门，适合精细制作现代贝斯音色。',
 'Studio Pre':'录音室风格饱和前级。Gain 加厚谐波，Character 改变染色性格，Mix 控制加入多少处理声。',
 'Punk Sans':'流行朋克方向的贝斯驱动音色。兼顾紧实低频与能穿过吉他的上部颗粒，提供 EQ、Blend 和可关闭箱体。',
 'ShedSpace':'节拍器＋持续和声音练习工具。可以设置拍号、细分、重音、根音和和弦，贝斯信号继续正常通过。',
 'DualComp':'低频压缩＋全频 FET 风格压缩。Tight、Punch、Crush 提供不同预设动态性格，再用 Mix 加回干声。',
 'DualGate':'双级噪声门。Hard 强调快速、紧的开关；Dynamic 希望在短音干净收尾的同时保留长音的自然衰减。',
 'Cognate Bitcrush':'数字降质效果：采样率、位深、Blocks 和 Glitch 制造颗粒、混叠与故障纹理。可用包络与 LFO 让变化跟随演奏或自行摆动。',
 'Cognate Chord':'持续和弦参考音工具，不是自动和声效果器。选择根音、和弦与音色后，它为音阶、和弦音和听觉练习提供背景。',
 'Cognate Hologram':'面向贝斯的立体声扩展。Microshift、Dimension、Hyper、Doubler 四种方式提供不同宽度；Low Mono 保持低频居中。',
 'Cognate Kinetic':'自动适应输入力度的包络滤波。正负 Range 决定向上或向下扫频，Speed 改变动作性格，也能加 LFO。',
 'Cognate Pultrick':'Pultec 风格均衡／染色。低频提升与衰减可以同时使用，获得不同于普通单段 EQ 的交互曲线。',
 'Cognate Metro':'节拍器工具。可用本机或全局速度，Follow Tempo 尝试跟随你的演奏；Gap 间歇静音帮助训练内在节拍。',
 'Cognate Ringmod':'环形调制与边带处理，能产生金属、铃声和科幻质感。载波可被包络、LFO 或音高追踪控制。',
 'Auto Wah':'自动哇音，按照触弦力度和设置的响应曲线扫频。也可直接控制 Wah 位置，或反转扫频方向。',
 'Auto Swell':'自动音量渐入，淡化拨弦音头，让音符像弓弦或铺底一样慢慢出现。Time 决定渐入时间。',
 'Beer Belly Enhancer':'把部分深低频转成更容易被小音箱听见的谐波。X-Over 选处理范围，Bass Bleed 加回原始低频。',
 'Bass Resonance':'低频共振增强。Frequency 把强化重心对准想要的低频位置，Amplitude 控制量，适合增加集中而非铺满的重量感。',
 'Cognate Polymath':'四声部复音移调：低八度、高八度、高两八度和自由移调声部。Tone、Attack 再塑造效果声的明暗和音头。',
 'Cognate Aperture':'高低切、截止点附近塑形与轻度磁带染色合一。可单独设置两端斜率，最后用 Output Level 配平音量。',
 'SubGlow':'低频增强与谐波塑形。Frequency 选中心，Glow 增加处理强度与性格，Mix 保留自然的原声比例。',
 'Uè Uè Wah':'人声元音式哇音。脚跟、中点、脚尖可选择元音，再用包络或 LFO 扫过它们，适合会“说话”的效果声。',
 'Box of Bass':'把多个实际捕捉的音箱、麦克风与房间声音并行混合。四层各自选类型、音色和电平，形成完整贝斯录音链。',
 'Wool':'受 Wal 双滤波前级启发的塑形器。低通和高通各自处理，再与原声混合；可放在链头改变乐器基础性格。',
 '4K-E':'四段英式调音台风格 EQ。高低两端可在搁架与钟形之间切换，中间两段可调 Q；Transformer 加入输出变压器式染色。',
 'Sonic Enhancer':'相位校正型增强器。Enhance 强化低频重量，Definition 强化高频细节，Output 配平音量；两项增强归零不等于完全旁通。',
 'Mammoth':'完整的现代贝斯处理链。低高频分开塑形，高频驱动与箱体搭配低频增强，最后混合以兼顾重量和清晰度。',
 'Big Red Mute Button':'专门的静音按钮。给它分配脚钉后可以快速静音，再按恢复；Fade 决定切换是立即还是平滑渐变。',
 'Analog Rack Delay':'简化的机架式延迟。可同步节奏、调整反馈，并用 Offset 为左右回声增加时间差。',
 'Groove':'透明取向的贝斯前级。Sub 切换深低频轮廓，半参数中频可选频率后增减；也可放在驱动后用作 EQ。',
 'Bass 3500':'Hartke HA3500 风格贝斯音箱。Tube 与 Solid State 两个前级可混合，另有压缩、十段 EQ、箱体拾音与 DI。',
 'Modern Tube':'贝斯管式过载。Driver 决定饱和度，Filter 调整过载声的高频，Blend 保住干净低频。',
 'DELAY3000':'复古／现代双性格延迟。除节奏与重复，还可用 Grit 加饱和、Smear 软化回声音头；单声道使用时官方建议 Pattern 设为 OFF。',
 'Doubler':'模拟双轨演奏的加倍器，以微小时间和音高差制造宽度。Mono 控制低频居中范围，不只是全局单声道开关。',
 'Crusher':'通过降低位深和采样率制造 Lo-Fi／数字破碎感。Stability 越低，采样率变化越不稳定，Filter 和 Mix 再修整结果。',
 'Octa':'复音八度器，提供低八度、高八度与高两八度，三个效果声可分别混入原声。Filter 调整八度声亮度。',
 'PolyShim':'低八度、原音与高八度三声部进入 Shimmer 混响。可分别调整声部，再用高低切修整空间尾音。',
 'Biotremology Tremolo':'可变波形的颤音效果，有普通与谐波模式。Chaos 加入随机感，分频可以保留低频或分开频段运动。',
 'Picking Fingers':'用音色与音头处理在拨片感和手指感之间转换。它不会改变实际演奏动作；Voice、Attack、Bite 调整听感特征。',
 'Arcadia U7':'录音室 DI／干净前级风格处理。Boost 逐级增加电平，Tone 提供七种宽范围音色曲线。',
 'Buffalo One':'四款 Pearce 风格电路模型的双通道前级。两通道分别设驱动与均衡后混合，并提供后级和限制器。',
 'Tape Delay':'多磁头磁带延迟。选择不同磁头组合获得节奏，Wow & Flutter、Tape Age、Drive 分别增加漂移、老化与饱和。',
 'Reverse Delay':'倒放延迟：回声反向播放，可加入调制。适合迷幻、渐起和环境音色，原声与效果比例由 Blend 控制。',
 'Ping Pong Delay':'左右来回弹跳的立体声延迟。可选数字／模拟性格，调整宽度、运动与滤波；需要立体声监听才能完整听到空间运动。',
 'Ping Pong Reverse Delay':'把倒放回声在左右声道之间传递。适合宽阔、电影感的铺底，使用 Blend 保留原始音头。',
 'Acoustic Voice Pro':'把拾音器直出处理成更像麦克风拾取的木吉他声音。可以选择吉他模型、麦克风及摆位；主要面向原声吉他。',
 'VOICE DC30':'英式清脆管式吉他音箱，含 Normal、Brilliant 与 Vib-Trem 路径，以及箱体拾音设置。',
 'MP1 Pro':'ADA MP-1 风格可编程前级加后级模型，三种 Voicing 在失真管式、干净管式与晶体管性格之间切换。',
 'Bass Cab Ultimate':'20 个贝斯箱体、每个四种性格，共 80 个 IR。Bright、Focused、Balanced、Extended 对应不同已制作好的拾音／DI 配比。',
 'SP Custom preamp':'尼龙弦电吉他压电前级的 EQ 重现。高低频、中频、Mid-cut 与输出，适合修整压电拾音的基础音色。'
};
export const dogood={ 'DoGood Odd Ones':'列车、柜体等特别空间的 43 个 IR', 'DoGood Work':'仓库、工地、酒庄等工作场所的 22 个 IR', 'DoGood Paris':'巴黎及周边真实场所的 30 个 IR', 'DoGood Korea':'韩国洞穴、艺术中心和寺庙等空间的 19 个 IR', 'DoGood 80s Gear':'经典 80 年代数字机架的 32 个混响 IR', 'DoGood BM7':'Bricasti M7 风格的 51 个混响 IR', 'DoGood Dungeon':'古堡、地牢及铸造厂空间的 28 个 IR', 'DoGood Grain Silo':'大型粮仓空间的 37 个 IR；长尾音可能消耗较多 DSP', 'DoGood Springs':'不同弹簧混响设备的 34 个 IR', 'DoGood Plate 140':'EMT 140 板式混响的 20 个 IR' };
for(const [name,text] of Object.entries(dogood)) summaries[name]=text+'。先选择 IR，再调干声、混响声和低切。这里的 IR 是固定捕捉，不是原设备全部算法参数的重现。';
